node {
   env.NODEJS_HOME = "${tool 'Node 7.10.1'}"
   env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}" 
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("sudheshpn/nodejsdemoapp:${commit_id}", '.').push()
     }
   }
}
